version: "3"

services:
  card-dive:
    container_name: card-dive
    image: card-dive
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - "3000:3000"
    restart: unless-stopped
    stdin_open: true