version: "3.7"

networks:
  nginxproxymanager_default:
    name: nginxproxymanager_default
    external: true

services:
  dev-card-dive-paris:
    container_name: dev-card-dive-paris
    image: dev-card-dive-paris
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    environment:
      - "REACT_APP_BASE_URL=${REACT_APP_BASE_URL}"
      - "REACT_APP_PANEL_PAGE=${REACT_APP_PANEL_PAGE}"
      - "NEXT_PUBLIC_GA_ID=${NEXT_PUBLIC_GA_ID}"
    stdin_open: true
    networks:
      - nginxproxymanager_default