FROM node:20.10.0-alpine

WORKDIR /app

# Copy source 
COPY . ./

# Remove existing node_modules and .next
#RUN rm -rf node_modules .next

# Install deps
RUN yarn

# Build
RUN yarn build

EXPOSE 3000

ENTRYPOINT [ "yarn", "start" ]