on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        secrets: inherit
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: '-rltgoDzvO --delete'
          SOURCE: './*'
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USER }}
          TARGET: '/var/www/card-dive-paris/'
          REMOTE_PORT: 22

      - name: Run container
        run: |
          ssh ${{ secrets.USER }}@${{ secrets.HOST }} 'chmod +x /var/www/card-dive-paris/run-app-deploy.sh'
          ssh ${{ secrets.USER }}@${{ secrets.HOST }} '/var/www/card-dive-paris/run-app-deploy.sh --prod'

      - name: Clean docker trash
        run: |
          ssh ${{ secrets.USER }}@${{ secrets.HOST }} 'docker image prune -f && docker volume prune -f && docker system prune -f'